Report erro in case we can't acquire the lock

diff --git a/bin/esy b/bin/esy
--- a/bin/esy
+++ b/bin/esy
@@ -18,4 +18,18 @@ fi
 mkdir -p "$ESY__PREFIX"
 LOCKFILENAME="$ESY__PREFIX/lock"
 
-"$SCRIPTDIR/flock" "$LOCKFILENAME" "$SCRIPTDIR/_esy" "$@"
+set +e
+
+# run bin/_esy and convert failure to exit 2 so we can distinguish between esy
+# failure and lock failure
+ESY_COMMAND="$SCRIPTDIR/_esy ${@}"
+"$SCRIPTDIR/flock" -n "$LOCKFILENAME" bash -c "$ESY_COMMAND || exit 2"
+
+retCode="$?"
+if [ $retCode -eq 1 ]; then
+  echo >&2 "error: another esy process is running, exiting...";
+  echo >&2 "       you can remove $LOCKFILENAME if you are sure that's not the case";
+  exit 1
+elif [ $retCode -ne 2 ]; then
+  exit 1
+fi
