Improvements (#4)
* Factor out package traverse into PackageDb module

* Move esyEnv module to lib/PackageEnvironment

* Fix `esy build` command to include complete env for packages

* Fix env var names accorsing to spec.

* Do not traverse deps in package db more than once

* Inlcude `build` and `clean` targets in ejected build

* Better escape for env vars

* Fix $<name>__install variable

* Fix typo in lib/Makefile.js

* Fix $cur__depends

* Make test packages depend on OCaml

* Fix package.json bin declaration

* Minor clean ups

* Simplify test Makefile

* Make `<name>.build` target do nothing if `_install/<name>` exists

* Add `rebuild` target

* Support peerDependencies in build command

* Strip flow types even if esy is installed.

* Put root package artifacts to _build/_install directly

* Move ocaml to peerDependencies

* Rename build to build-eject, impl for build, shell commands

* Fix test Makefile

* Fix chmod for lib/PackageEnvironment.js

* Normalize env var names and dix PATH/MAN_PATH

* Prepare _install dir for packages

* Handle namespaced packages: @namespace/name

* Better failure handling

* Move code around

* Refactor env calculation

* Update test packages

* Execute arbitrary commands in env

* Add `esy clean` command

* Fix global scope only to include env from own dep tree

* Simplify test packages, make them not to use solvuu-build

* Refactor Makefile generation, better shell command

* Fix rendering Makefile defines

We didn't escape shell vars, now we do.

diff --git a/.bin/esy b/.bin/esy
--- a/.bin/esy
+++ b/.bin/esy
@@ -25,13 +25,32 @@ SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 # Capture the error output
 # Capturing stderr is very important to prevent nodejs from setting
 # stderr to nonblocking mode
-SETENVCMD=$($SCRIPTDIR/esy.js "$@" $CURDIR 2>&1)
-if [ $? -ne 0 ]; then
+
+if [ "$1" == "build" ] || [ "$1" == "shell" ] || [ "$1" == "clean" ]; then
+  MAKEFILE=`/usr/bin/env node $SCRIPTDIR/esy.js build-eject $CURDIR 2>&1`
+  if [ $? -ne 0 ]; then
+    echo "Failed to get dependency:"
+    printf "%s\n" "$MAKEFILE" >&2
+    exit 1
+  fi
+  make -s -f <(echo "$MAKEFILE") "$1"
+
+elif [ "$1" == "build-eject" ]; then
+  exec /usr/bin/env node $SCRIPTDIR/esy.js build-eject $CURDIR
+
+else
+  SETENVCMD=$(/usr/bin/env node $SCRIPTDIR/esy.js $CURDIR 2>&1)
+  if [ $? -ne 0 ]; then
     echo "Failed to get dependency:"
     printf "%s\n" "$SETENVCMD" >&2
     exit 1
-fi
-# Use like this:
-# $(esy) && command
-echo "$SETENVCMD"
+  fi
 
+  if [ "$1" != "" ]; then
+    export ESY__SANDBOX=$PWD
+    eval "$SETENVCMD"
+    exec "$@"
+  else
+    echo "$SETENVCMD"
+  fi
+fi
